version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
volumes:
  db-volume:
